### ISSUE TITLE
Error in task apply nvm.sh and set default version

### ISSUE THREAD

**Issue by stefanocog** [William-Yeh/ansible-nvm-nodejs#1]
Hi, i use this role with vagrant and ansible 1.7.2 on ubuntu trusty to one month and not have any problem, today i get this error:

TASK: [node | apply nvm.sh and set default version] **************************\* 
fatal: [dev] => Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/runner/**init**.py", line 561, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 666, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 756, in _executor_internal_inner
    if not utils.check_conditional(cond, self.basedir, inject, fail_on_undefined=self.error_on_undefined_vars):
  File "/usr/lib/python2.7/dist-packages/ansible/utils/__init__.py", line 258, in check_conditional
    conditional = template.template(basedir, presented, inject)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/template.py", line 115, in template
    varname = template_from_string(basedir, varname, vars, fail_on_undefined)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/template.py", line 357, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 3 column 17 (char 45)

FATAL: all hosts have already failed -- aborting

Any idea?

**Comment by William-Yeh** [comment]
Sorry but this role is deprecated.  As stated in README file:

> **[Deprecated!!] Use [williamyeh.nodejs](https://github.com/William-Yeh/ansible-nodejs) instead.** 

If you insist on using `nvm`, I think there're many alternatives in Ansible Galaxy.
